# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  #  awse_commerce_service client class.
  class AwseCommerceServiceClient
    # Singleton access to awse_commerce_service_binding controller.
    # @return [AWSECommerceServiceBindingController] Returns the controller instance.
    def awse_commerce_service_binding
      AWSECommerceServiceBindingController.instance
    end

    # Returns the configuration class for easy access.
    # @return [Configuration] Returns the actual configuration class.
    def config
      Configuration
    end
  end
end
