# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # All configuration including auth info and base URI for the API access
  # are configured in this class.
  class Configuration
    # Set the array parameter serialization method.
    # (allowed: indexed, unindexed, plain, csv, tsv, psv)
    @array_serialization = 'indexed'

    # An enum for SDK environments.
    class Environment
      ENVIRONMENT = [PRODUCTION = 0].freeze
    end

    # An enum for API servers.
    class Server
      SERVER = [AWSECOMMERCESERVICEPORT = 0, AWSECOMMERCESERVICEPORTCA = 1, AWSECOMMERCESERVICEPORTCN = 2, AWSECOMMERCESERVICEPORTDE = 3, AWSECOMMERCESERVICEPORTES = 4, AWSECOMMERCESERVICEPORTFR = 5, AWSECOMMERCESERVICEPORTIN = 6, AWSECOMMERCESERVICEPORTIT = 7, AWSECOMMERCESERVICEPORTJP = 8, AWSECOMMERCESERVICEPORTUK = 9, AWSECOMMERCESERVICEPORTUS = 10].freeze
    end

    # The environment in which the SDK is running.
    @environment = Environment::PRODUCTION

    # All the environments the SDK can run in.
    @environments = {
      Environment::PRODUCTION => {
        Server::AWSECOMMERCESERVICEPORT => 'https://webservices.amazon.com/onca/soap?Service=AWSECommerceService',
        Server::AWSECOMMERCESERVICEPORTCA => 'https://webservices.amazon.ca/onca/soap?Service=AWSECommerceService',
        Server::AWSECOMMERCESERVICEPORTCN => 'https://webservices.amazon.cn/onca/soap?Service=AWSECommerceService',
        Server::AWSECOMMERCESERVICEPORTDE => 'https://webservices.amazon.de/onca/soap?Service=AWSECommerceService',
        Server::AWSECOMMERCESERVICEPORTES => 'https://webservices.amazon.es/onca/soap?Service=AWSECommerceService',
        Server::AWSECOMMERCESERVICEPORTFR => 'https://webservices.amazon.fr/onca/soap?Service=AWSECommerceService',
        Server::AWSECOMMERCESERVICEPORTIN => 'https://webservices.amazon.in/onca/soap?Service=AWSECommerceService',
        Server::AWSECOMMERCESERVICEPORTIT => 'https://webservices.amazon.it/onca/soap?Service=AWSECommerceService',
        Server::AWSECOMMERCESERVICEPORTJP => 'https://webservices.amazon.co.jp/onca/soap?Service=AWSECommerceService',
        Server::AWSECOMMERCESERVICEPORTUK => 'https://webservices.amazon.co.uk/onca/soap?Service=AWSECommerceService',
        Server::AWSECOMMERCESERVICEPORTUS => 'https://webservices.amazon.com/onca/soap?Service=AWSECommerceService'
      }
    }

    # Generates the appropriate base URI for the environment and the server.
    # @param [Configuration::Server] The server enum for which the base URI is
    # required.
    # @return [String] The base URI.
    def self.get_base_uri(server = Server::AWSECOMMERCESERVICEPORT)
      environments[environment][server]
    end

    # The attribute accessors for public properties.
    class << self
      attr_accessor :array_serialization
      attr_accessor :environment
      attr_accessor :environments
    end
  end
end
