# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Accessories Model.
  class Accessories < BaseModel
    # TODO: Write general description for this method
    # @return [List of Accessory]
    attr_accessor :accessory

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['accessory'] = 'Accessory'
      @_hash
    end

    def initialize(accessory = nil)
      @accessory = accessory
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      accessory = nil
      unless hash['Accessory'].nil?
        accessory = []
        hash['Accessory'].each do |structure|
          accessory << (Accessory.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      Accessories.new(accessory)
    end
  end
end
