# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Action.
  class ActionEnum
    ACTION_ENUM = [
      # TODO: Write general description for MOVETOCART
      MOVETOCART = 'MoveToCart'.freeze,

      # TODO: Write general description for SAVEFORLATER
      SAVEFORLATER = 'SaveForLater'.freeze
    ].freeze
  end
end
