# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # AlternateVersions Model.
  class AlternateVersions < BaseModel
    # TODO: Write general description for this method
    # @return [List of AlternateVersion]
    attr_accessor :alternate_version

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['alternate_version'] = 'AlternateVersion'
      @_hash
    end

    def initialize(alternate_version = nil)
      @alternate_version = alternate_version
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      alternate_version = nil
      unless hash['AlternateVersion'].nil?
        alternate_version = []
        hash['AlternateVersion'].each do |structure|
          alternate_version << (AlternateVersion.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      AlternateVersions.new(alternate_version)
    end
  end
end
