# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # AlternateVersion Model.
  class AlternateVersion < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :asin

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :title

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :binding

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['asin'] = 'ASIN'
      @_hash['title'] = 'Title'
      @_hash['binding'] = 'Binding'
      @_hash
    end

    def initialize(asin = nil,
                   title = nil,
                   binding = nil)
      @asin = asin
      @title = title
      @binding = binding
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      asin = hash['ASIN']
      title = hash['Title']
      binding = hash['Binding']

      # Create object from extracted values.
      AlternateVersion.new(asin,
                           title,
                           binding)
    end
  end
end
