# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Arguments Model.
  class Arguments < BaseModel
    # TODO: Write general description for this method
    # @return [List of Argument]
    attr_accessor :argument

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['argument'] = 'Argument'
      @_hash
    end

    def initialize(argument = nil)
      @argument = argument
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      argument = nil
      unless hash['Argument'].nil?
        argument = []
        hash['Argument'].each do |structure|
          argument << (Argument.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      Arguments.new(argument)
    end
  end
end
