# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # AudienceRating.
  class AudienceRatingEnum
    AUDIENCE_RATING_ENUM = [
      # TODO: Write general description for G
      G = 'G'.freeze,

      # TODO: Write general description for PG
      PG = 'PG'.freeze,

      # TODO: Write general description for PG13
      PG13 = 'PG-13'.freeze,

      # TODO: Write general description for R
      R = 'R'.freeze,

      # TODO: Write general description for NC17
      NC17 = 'NC-17'.freeze,

      # TODO: Write general description for NR
      NR = 'NR'.freeze,

      # TODO: Write general description for UNRATED
      UNRATED = 'Unrated'.freeze,

      # TODO: Write general description for ENUM_6
      ENUM_6 = '6'.freeze,

      # TODO: Write general description for ENUM_12
      ENUM_12 = '12'.freeze,

      # TODO: Write general description for ENUM_16
      ENUM_16 = '16'.freeze,

      # TODO: Write general description for ENUM_18
      ENUM_18 = '18'.freeze,

      # TODO: Write general description for FAMILYVIEWING
      FAMILYVIEWING = 'FamilyViewing'.freeze
    ].freeze
  end
end
