# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Availability.
  class AvailabilityEnum
    AVAILABILITY_ENUM = [
      # TODO: Write general description for AVAILABLE
      AVAILABLE = 'Available'.freeze
    ].freeze
  end
end
