# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # AvailabilityAttributes Model.
  class AvailabilityAttributes < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :availability_type

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :is_preorder

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :minimum_hours

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :maximum_hours

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['availability_type'] = 'AvailabilityType'
      @_hash['is_preorder'] = 'IsPreorder'
      @_hash['minimum_hours'] = 'MinimumHours'
      @_hash['maximum_hours'] = 'MaximumHours'
      @_hash
    end

    def initialize(availability_type = nil,
                   is_preorder = nil,
                   minimum_hours = nil,
                   maximum_hours = nil)
      @availability_type = availability_type
      @is_preorder = is_preorder
      @minimum_hours = minimum_hours
      @maximum_hours = maximum_hours
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      availability_type = hash['AvailabilityType']
      is_preorder = hash['IsPreorder']
      minimum_hours = hash['MinimumHours']
      maximum_hours = hash['MaximumHours']

      # Create object from extracted values.
      AvailabilityAttributes.new(availability_type,
                                 is_preorder,
                                 minimum_hours,
                                 maximum_hours)
    end
  end
end
