# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Bin Model.
  class Bin < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :bin_name

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :bin_item_count

    # TODO: Write general description for this method
    # @return [List of BinParameter]
    attr_accessor :bin_parameter

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['bin_name'] = 'BinName'
      @_hash['bin_item_count'] = 'BinItemCount'
      @_hash['bin_parameter'] = 'BinParameter'
      @_hash
    end

    def initialize(bin_name = nil,
                   bin_item_count = nil,
                   bin_parameter = nil)
      @bin_name = bin_name
      @bin_item_count = bin_item_count
      @bin_parameter = bin_parameter
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      bin_name = hash['BinName']
      bin_item_count = hash['BinItemCount']
      # Parameter is an array, so we need to iterate through it
      bin_parameter = nil
      unless hash['BinParameter'].nil?
        bin_parameter = []
        hash['BinParameter'].each do |structure|
          bin_parameter << (BinParameter.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      Bin.new(bin_name,
              bin_item_count,
              bin_parameter)
    end
  end
end
