# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # BrowseNodeLookupRequest Model.
  class BrowseNodeLookupRequest < BaseModel
    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :browse_node_id

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :response_group

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['browse_node_id'] = 'BrowseNodeId'
      @_hash['response_group'] = 'ResponseGroup'
      @_hash
    end

    def initialize(browse_node_id = nil,
                   response_group = nil)
      @browse_node_id = browse_node_id
      @response_group = response_group
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      browse_node_id = hash['BrowseNodeId']
      response_group = hash['ResponseGroup']

      # Create object from extracted values.
      BrowseNodeLookupRequest.new(browse_node_id,
                                  response_group)
    end
  end
end
