# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # CartCreateRequestMsg Model.
  class CartCreateRequestMsg < BaseModel
    # TODO: Write general description for this method
    # @return [CartCreate]
    attr_accessor :body

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['body'] = 'body'
      @_hash
    end

    def initialize(body = nil)
      @body = body
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      body = CartCreate.from_hash(hash['body']) if hash['body']

      # Create object from extracted values.
      CartCreateRequestMsg.new(body)
    end
  end
end
