# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Cart Model.
  class Cart < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :cart_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :hmac

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :url_encoded_hmac

    # TODO: Write general description for this method
    # @return [Request162]
    attr_accessor :request

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :purchase_url

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :mobile_cart_url

    # TODO: Write general description for this method
    # @return [Price]
    attr_accessor :sub_total

    # TODO: Write general description for this method
    # @return [CartItems]
    attr_accessor :cart_items

    # TODO: Write general description for this method
    # @return [SavedForLaterItems]
    attr_accessor :saved_for_later_items

    # TODO: Write general description for this method
    # @return [SimilarProducts]
    attr_accessor :similar_products

    # TODO: Write general description for this method
    # @return [TopSellers]
    attr_accessor :top_sellers

    # TODO: Write general description for this method
    # @return [NewReleases]
    attr_accessor :new_releases

    # TODO: Write general description for this method
    # @return [SimilarViewedProducts]
    attr_accessor :similar_viewed_products

    # TODO: Write general description for this method
    # @return [OtherCategoriesSimilarProducts]
    attr_accessor :other_categories_similar_products

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['cart_id'] = 'CartId'
      @_hash['hmac'] = 'HMAC'
      @_hash['url_encoded_hmac'] = 'URLEncodedHMAC'
      @_hash['request'] = 'Request'
      @_hash['purchase_url'] = 'PurchaseURL'
      @_hash['mobile_cart_url'] = 'MobileCartURL'
      @_hash['sub_total'] = 'SubTotal'
      @_hash['cart_items'] = 'CartItems'
      @_hash['saved_for_later_items'] = 'SavedForLaterItems'
      @_hash['similar_products'] = 'SimilarProducts'
      @_hash['top_sellers'] = 'TopSellers'
      @_hash['new_releases'] = 'NewReleases'
      @_hash['similar_viewed_products'] = 'SimilarViewedProducts'
      @_hash['other_categories_similar_products'] = 'OtherCategoriesSimilarProducts'
      @_hash
    end

    def initialize(cart_id = nil,
                   hmac = nil,
                   url_encoded_hmac = nil,
                   request = nil,
                   purchase_url = nil,
                   mobile_cart_url = nil,
                   sub_total = nil,
                   cart_items = nil,
                   saved_for_later_items = nil,
                   similar_products = nil,
                   top_sellers = nil,
                   new_releases = nil,
                   similar_viewed_products = nil,
                   other_categories_similar_products = nil)
      @cart_id = cart_id
      @hmac = hmac
      @url_encoded_hmac = url_encoded_hmac
      @request = request
      @purchase_url = purchase_url
      @mobile_cart_url = mobile_cart_url
      @sub_total = sub_total
      @cart_items = cart_items
      @saved_for_later_items = saved_for_later_items
      @similar_products = similar_products
      @top_sellers = top_sellers
      @new_releases = new_releases
      @similar_viewed_products = similar_viewed_products
      @other_categories_similar_products = other_categories_similar_products
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      cart_id = hash['CartId']
      hmac = hash['HMAC']
      url_encoded_hmac = hash['URLEncodedHMAC']
      request = Request162.from_hash(hash['Request']) if hash['Request']
      purchase_url = hash['PurchaseURL']
      mobile_cart_url = hash['MobileCartURL']
      sub_total = Price.from_hash(hash['SubTotal']) if hash['SubTotal']
      cart_items = CartItems.from_hash(hash['CartItems']) if hash['CartItems']
      saved_for_later_items = SavedForLaterItems.from_hash(hash['SavedForLaterItems']) if
        hash['SavedForLaterItems']
      similar_products = SimilarProducts.from_hash(hash['SimilarProducts']) if
        hash['SimilarProducts']
      top_sellers = TopSellers.from_hash(hash['TopSellers']) if
        hash['TopSellers']
      new_releases = NewReleases.from_hash(hash['NewReleases']) if
        hash['NewReleases']
      similar_viewed_products = SimilarViewedProducts.from_hash(hash['SimilarViewedProducts']) if
        hash['SimilarViewedProducts']
      other_categories_similar_products = OtherCategoriesSimilarProducts.from_hash(hash['OtherCategoriesSimilarProducts']) if
        hash['OtherCategoriesSimilarProducts']

      # Create object from extracted values.
      Cart.new(cart_id,
               hmac,
               url_encoded_hmac,
               request,
               purchase_url,
               mobile_cart_url,
               sub_total,
               cart_items,
               saved_for_later_items,
               similar_products,
               top_sellers,
               new_releases,
               similar_viewed_products,
               other_categories_similar_products)
    end
  end
end
