# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # CartClearRequest Model.
  class CartClearRequest < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :cart_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :hmac

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :merge_cart

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :response_group

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['cart_id'] = 'CartId'
      @_hash['hmac'] = 'HMAC'
      @_hash['merge_cart'] = 'MergeCart'
      @_hash['response_group'] = 'ResponseGroup'
      @_hash
    end

    def initialize(cart_id = nil,
                   hmac = nil,
                   merge_cart = nil,
                   response_group = nil)
      @cart_id = cart_id
      @hmac = hmac
      @merge_cart = merge_cart
      @response_group = response_group
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      cart_id = hash['CartId']
      hmac = hash['HMAC']
      merge_cart = hash['MergeCart']
      response_group = hash['ResponseGroup']

      # Create object from extracted values.
      CartClearRequest.new(cart_id,
                           hmac,
                           merge_cart,
                           response_group)
    end
  end
end
