# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # CartCreateRequest55 Model.
  class CartCreateRequest55 < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :merge_cart

    # TODO: Write general description for this method
    # @return [Items]
    attr_accessor :items

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :response_group

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['merge_cart'] = 'MergeCart'
      @_hash['items'] = 'Items'
      @_hash['response_group'] = 'ResponseGroup'
      @_hash
    end

    def initialize(merge_cart = nil,
                   items = nil,
                   response_group = nil)
      @merge_cart = merge_cart
      @items = items
      @response_group = response_group
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      merge_cart = hash['MergeCart']
      items = Items.from_hash(hash['Items']) if hash['Items']
      response_group = hash['ResponseGroup']

      # Create object from extracted values.
      CartCreateRequest55.new(merge_cart,
                              items,
                              response_group)
    end
  end
end
