# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # CatalogNumberList Model.
  class CatalogNumberList < BaseModel
    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :catalog_number_list_element

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['catalog_number_list_element'] = 'CatalogNumberListElement'
      @_hash
    end

    def initialize(catalog_number_list_element = nil)
      @catalog_number_list_element = catalog_number_list_element
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      catalog_number_list_element = hash['CatalogNumberListElement']

      # Create object from extracted values.
      CatalogNumberList.new(catalog_number_list_element)
    end
  end
end
