# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Children Model.
  class Children < BaseModel
    # TODO: Write general description for this method
    # @return [List of BrowseNode]
    attr_accessor :browse_node

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['browse_node'] = 'BrowseNode'
      @_hash
    end

    def initialize(browse_node = nil)
      @browse_node = browse_node
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      browse_node = nil
      unless hash['BrowseNode'].nil?
        browse_node = []
        hash['BrowseNode'].each do |structure|
          browse_node << (BrowseNode.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      Children.new(browse_node)
    end
  end
end
