# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Collections Model.
  class Collections < BaseModel
    # TODO: Write general description for this method
    # @return [List of Collection]
    attr_accessor :collection

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['collection'] = 'Collection'
      @_hash
    end

    def initialize(collection = nil)
      @collection = collection
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      collection = nil
      unless hash['Collection'].nil?
        collection = []
        hash['Collection'].each do |structure|
          collection << (Collection.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      Collections.new(collection)
    end
  end
end
