# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Condition.
  class ConditionEnum
    CONDITION_ENUM = [
      # TODO: Write general description for ALL
      ALL = 'All'.freeze,

      # TODO: Write general description for NEW
      NEW = 'New'.freeze,

      # TODO: Write general description for USED
      USED = 'Used'.freeze,

      # TODO: Write general description for COLLECTIBLE
      COLLECTIBLE = 'Collectible'.freeze,

      # TODO: Write general description for REFURBISHED
      REFURBISHED = 'Refurbished'.freeze
    ].freeze
  end
end
