# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # CorrectedQuery Model.
  class CorrectedQuery < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :keywords

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :message

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['keywords'] = 'Keywords'
      @_hash['message'] = 'Message'
      @_hash
    end

    def initialize(keywords = nil,
                   message = nil)
      @keywords = keywords
      @message = message
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      keywords = hash['Keywords']
      message = hash['Message']

      # Create object from extracted values.
      CorrectedQuery.new(keywords,
                         message)
    end
  end
end
