# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Creator Model.
  class Creator < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :role

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['role'] = 'Role'
      @_hash
    end

    def initialize(role = nil)
      @role = role
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      role = hash['Role']

      # Create object from extracted values.
      Creator.new(role)
    end
  end
end
