# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # CustomerReviews Model.
  class CustomerReviews < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :i_frame_url

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :has_reviews

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['i_frame_url'] = 'IFrameURL'
      @_hash['has_reviews'] = 'HasReviews'
      @_hash
    end

    def initialize(i_frame_url = nil,
                   has_reviews = nil)
      @i_frame_url = i_frame_url
      @has_reviews = has_reviews
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      i_frame_url = hash['IFrameURL']
      has_reviews = hash['HasReviews']

      # Create object from extracted values.
      CustomerReviews.new(i_frame_url,
                          has_reviews)
    end
  end
end
