# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Disc Model.
  class Disc < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :number

    # TODO: Write general description for this method
    # @return [List of Track]
    attr_accessor :track

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['number'] = 'Number'
      @_hash['track'] = 'Track'
      @_hash
    end

    def initialize(number = nil,
                   track = nil)
      @number = number
      @track = track
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      number = hash['Number']
      # Parameter is an array, so we need to iterate through it
      track = nil
      unless hash['Track'].nil?
        track = []
        hash['Track'].each do |structure|
          track << (Track.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      Disc.new(number,
               track)
    end
  end
end
