# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # EANList Model.
  class EANList < BaseModel
    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :ean_list_element

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['ean_list_element'] = 'EANListElement'
      @_hash
    end

    def initialize(ean_list_element = nil)
      @ean_list_element = ean_list_element
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      ean_list_element = hash['EANListElement']

      # Create object from extracted values.
      EANList.new(ean_list_element)
    end
  end
end
