# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # EditorialReviews Model.
  class EditorialReviews < BaseModel
    # TODO: Write general description for this method
    # @return [List of EditorialReview]
    attr_accessor :editorial_review

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['editorial_review'] = 'EditorialReview'
      @_hash
    end

    def initialize(editorial_review = nil)
      @editorial_review = editorial_review
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      editorial_review = nil
      unless hash['EditorialReview'].nil?
        editorial_review = []
        hash['EditorialReview'].each do |structure|
          editorial_review << (EditorialReview.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      EditorialReviews.new(editorial_review)
    end
  end
end
