# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # EditorialReview Model.
  class EditorialReview < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :source

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :content

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :is_link_suppressed

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['source'] = 'Source'
      @_hash['content'] = 'Content'
      @_hash['is_link_suppressed'] = 'IsLinkSuppressed'
      @_hash
    end

    def initialize(source = nil,
                   content = nil,
                   is_link_suppressed = nil)
      @source = source
      @content = content
      @is_link_suppressed = is_link_suppressed
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      source = hash['Source']
      content = hash['Content']
      is_link_suppressed = hash['IsLinkSuppressed']

      # Create object from extracted values.
      EditorialReview.new(source,
                          content,
                          is_link_suppressed)
    end
  end
end
