# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Error Model.
  class Error < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :message

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['code'] = 'Code'
      @_hash['message'] = 'Message'
      @_hash
    end

    def initialize(code = nil,
                   message = nil)
      @code = code
      @message = message
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      code = hash['Code']
      message = hash['Message']

      # Create object from extracted values.
      Error.new(code,
                message)
    end
  end
end
