# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # HTTPHeaders Model.
  class HTTPHeaders < BaseModel
    # TODO: Write general description for this method
    # @return [List of Header]
    attr_accessor :header

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['header'] = 'Header'
      @_hash
    end

    def initialize(header = nil)
      @header = header
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      header = nil
      unless hash['Header'].nil?
        header = []
        hash['Header'].each do |structure|
          header << (Header.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      HTTPHeaders.new(header)
    end
  end
end
