# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # IdType.
  class IdTypeEnum
    ID_TYPE_ENUM = [
      # TODO: Write general description for ASIN
      ASIN = 'ASIN'.freeze,

      # TODO: Write general description for UPC
      UPC = 'UPC'.freeze,

      # TODO: Write general description for SKU
      SKU = 'SKU'.freeze,

      # TODO: Write general description for EAN
      EAN = 'EAN'.freeze,

      # TODO: Write general description for ISBN
      ISBN = 'ISBN'.freeze
    ].freeze
  end
end
