# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # ImageSet Model.
  class ImageSet < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :category

    # TODO: Write general description for this method
    # @return [Image]
    attr_accessor :swatch_image

    # TODO: Write general description for this method
    # @return [Image]
    attr_accessor :small_image

    # TODO: Write general description for this method
    # @return [Image]
    attr_accessor :thumbnail_image

    # TODO: Write general description for this method
    # @return [Image]
    attr_accessor :tiny_image

    # TODO: Write general description for this method
    # @return [Image]
    attr_accessor :medium_image

    # TODO: Write general description for this method
    # @return [Image]
    attr_accessor :large_image

    # TODO: Write general description for this method
    # @return [Image]
    attr_accessor :hi_res_image

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['category'] = 'Category'
      @_hash['swatch_image'] = 'SwatchImage'
      @_hash['small_image'] = 'SmallImage'
      @_hash['thumbnail_image'] = 'ThumbnailImage'
      @_hash['tiny_image'] = 'TinyImage'
      @_hash['medium_image'] = 'MediumImage'
      @_hash['large_image'] = 'LargeImage'
      @_hash['hi_res_image'] = 'HiResImage'
      @_hash
    end

    def initialize(category = nil,
                   swatch_image = nil,
                   small_image = nil,
                   thumbnail_image = nil,
                   tiny_image = nil,
                   medium_image = nil,
                   large_image = nil,
                   hi_res_image = nil)
      @category = category
      @swatch_image = swatch_image
      @small_image = small_image
      @thumbnail_image = thumbnail_image
      @tiny_image = tiny_image
      @medium_image = medium_image
      @large_image = large_image
      @hi_res_image = hi_res_image
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      category = hash['Category']
      swatch_image = Image.from_hash(hash['SwatchImage']) if
        hash['SwatchImage']
      small_image = Image.from_hash(hash['SmallImage']) if hash['SmallImage']
      thumbnail_image = Image.from_hash(hash['ThumbnailImage']) if
        hash['ThumbnailImage']
      tiny_image = Image.from_hash(hash['TinyImage']) if hash['TinyImage']
      medium_image = Image.from_hash(hash['MediumImage']) if
        hash['MediumImage']
      large_image = Image.from_hash(hash['LargeImage']) if hash['LargeImage']
      hi_res_image = Image.from_hash(hash['HiResImage']) if hash['HiResImage']

      # Create object from extracted values.
      ImageSet.new(category,
                   swatch_image,
                   small_image,
                   thumbnail_image,
                   tiny_image,
                   medium_image,
                   large_image,
                   hi_res_image)
    end
  end
end
