# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Image Model.
  class Image < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :url

    # TODO: Write general description for this method
    # @return [DecimalWithUnits]
    attr_accessor :height

    # TODO: Write general description for this method
    # @return [DecimalWithUnits]
    attr_accessor :width

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :is_verified

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['url'] = 'URL'
      @_hash['height'] = 'Height'
      @_hash['width'] = 'Width'
      @_hash['is_verified'] = 'IsVerified'
      @_hash
    end

    def initialize(url = nil,
                   height = nil,
                   width = nil,
                   is_verified = nil)
      @url = url
      @height = height
      @width = width
      @is_verified = is_verified
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      url = hash['URL']
      height = DecimalWithUnits.from_hash(hash['Height']) if hash['Height']
      width = DecimalWithUnits.from_hash(hash['Width']) if hash['Width']
      is_verified = hash['IsVerified']

      # Create object from extracted values.
      Image.new(url,
                height,
                width,
                is_verified)
    end
  end
end
