# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # ImageSets Model.
  class ImageSets < BaseModel
    # TODO: Write general description for this method
    # @return [List of ImageSet]
    attr_accessor :image_set

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['image_set'] = 'ImageSet'
      @_hash
    end

    def initialize(image_set = nil)
      @image_set = image_set
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      image_set = nil
      unless hash['ImageSet'].nil?
        image_set = []
        hash['ImageSet'].each do |structure|
          image_set << (ImageSet.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      ImageSets.new(image_set)
    end
  end
end
