# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Item Model.
  class Item < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :asin

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :offer_listing_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :quantity

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :associate_tag

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :list_item_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['asin'] = 'ASIN'
      @_hash['offer_listing_id'] = 'OfferListingId'
      @_hash['quantity'] = 'Quantity'
      @_hash['associate_tag'] = 'AssociateTag'
      @_hash['list_item_id'] = 'ListItemId'
      @_hash
    end

    def initialize(asin = nil,
                   offer_listing_id = nil,
                   quantity = nil,
                   associate_tag = nil,
                   list_item_id = nil)
      @asin = asin
      @offer_listing_id = offer_listing_id
      @quantity = quantity
      @associate_tag = associate_tag
      @list_item_id = list_item_id
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      asin = hash['ASIN']
      offer_listing_id = hash['OfferListingId']
      quantity = hash['Quantity']
      associate_tag = hash['AssociateTag']
      list_item_id = hash['ListItemId']

      # Create object from extracted values.
      Item.new(asin,
               offer_listing_id,
               quantity,
               associate_tag,
               list_item_id)
    end
  end
end
