# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Item34 Model.
  class Item34 < BaseModel
    # TODO: Write general description for this method
    # @return [ActionEnum]
    attr_accessor :action

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :cart_item_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :quantity

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['action'] = 'Action'
      @_hash['cart_item_id'] = 'CartItemId'
      @_hash['quantity'] = 'Quantity'
      @_hash
    end

    def initialize(action = nil,
                   cart_item_id = nil,
                   quantity = nil)
      @action = action
      @cart_item_id = cart_item_id
      @quantity = quantity
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      action = hash['Action']
      cart_item_id = hash['CartItemId']
      quantity = hash['Quantity']

      # Create object from extracted values.
      Item34.new(action,
                 cart_item_id,
                 quantity)
    end
  end
end
