# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # ItemAttributes Model.
  class ItemAttributes < BaseModel
    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :actor

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :artist

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :aspect_ratio

    # TODO: Write general description for this method
    # @return [AudienceRatingEnum]
    attr_accessor :audience_rating

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :audio_format

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :author

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :binding

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :brand

    # TODO: Write general description for this method
    # @return [CatalogNumberList]
    attr_accessor :catalog_number_list

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :category

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :cero_age_rating

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :clothing_size

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :color

    # TODO: Write general description for this method
    # @return [List of Creator]
    attr_accessor :creator

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :department

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :director

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :ean

    # TODO: Write general description for this method
    # @return [EANList]
    attr_accessor :ean_list

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :edition

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :eisbn

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :energy_efficiency_class

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :episode_sequence

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :esrb_age_rating

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :feature

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :format

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :genre

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :hardware_platform

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :hazardous_material_type

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :is_adult_product

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :is_autographed

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :isbn

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :is_eligible_for_trade_in

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :is_memorabilia

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :issues_per_year

    # TODO: Write general description for this method
    # @return [ItemDimensions]
    attr_accessor :item_dimensions

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :item_part_number

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :label

    # TODO: Write general description for this method
    # @return [Languages]
    attr_accessor :languages

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :legal_disclaimer

    # TODO: Write general description for this method
    # @return [Price]
    attr_accessor :list_price

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :magazine_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :manufacturer

    # TODO: Write general description for this method
    # @return [DecimalWithUnits]
    attr_accessor :manufacturer_maximum_age

    # TODO: Write general description for this method
    # @return [DecimalWithUnits]
    attr_accessor :manufacturer_minimum_age

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :manufacturer_parts_warranty_description

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :media_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :model

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :model_year

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :mpn

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :number_of_discs

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :number_of_issues

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :number_of_items

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :number_of_pages

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :number_of_tracks

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :operating_system

    # TODO: Write general description for this method
    # @return [PackageDimensions]
    attr_accessor :package_dimensions

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :package_quantity

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :part_number

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :picture_format

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :platform

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :product_group

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :product_type_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :product_type_subcategory

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :publication_date

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :publisher

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :region_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :release_date

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :season_sequence

    # TODO: Write general description for this method
    # @return [DecimalWithUnits]
    attr_accessor :running_time

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :seikodo_product_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :size

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :sku

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :studio

    # TODO: Write general description for this method
    # @return [NonNegativeIntegerWithUnits]
    attr_accessor :subscription_length

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :title

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :track_sequence

    # TODO: Write general description for this method
    # @return [Price]
    attr_accessor :trade_in_value

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :upc

    # TODO: Write general description for this method
    # @return [UPCList]
    attr_accessor :upc_list

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :warranty

    # TODO: Write general description for this method
    # @return [Price]
    attr_accessor :weee_tax_value

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['actor'] = 'Actor'
      @_hash['artist'] = 'Artist'
      @_hash['aspect_ratio'] = 'AspectRatio'
      @_hash['audience_rating'] = 'AudienceRating'
      @_hash['audio_format'] = 'AudioFormat'
      @_hash['author'] = 'Author'
      @_hash['binding'] = 'Binding'
      @_hash['brand'] = 'Brand'
      @_hash['catalog_number_list'] = 'CatalogNumberList'
      @_hash['category'] = 'Category'
      @_hash['cero_age_rating'] = 'CEROAgeRating'
      @_hash['clothing_size'] = 'ClothingSize'
      @_hash['color'] = 'Color'
      @_hash['creator'] = 'Creator'
      @_hash['department'] = 'Department'
      @_hash['director'] = 'Director'
      @_hash['ean'] = 'EAN'
      @_hash['ean_list'] = 'EANList'
      @_hash['edition'] = 'Edition'
      @_hash['eisbn'] = 'EISBN'
      @_hash['energy_efficiency_class'] = 'EnergyEfficiencyClass'
      @_hash['episode_sequence'] = 'EpisodeSequence'
      @_hash['esrb_age_rating'] = 'ESRBAgeRating'
      @_hash['feature'] = 'Feature'
      @_hash['format'] = 'Format'
      @_hash['genre'] = 'Genre'
      @_hash['hardware_platform'] = 'HardwarePlatform'
      @_hash['hazardous_material_type'] = 'HazardousMaterialType'
      @_hash['is_adult_product'] = 'IsAdultProduct'
      @_hash['is_autographed'] = 'IsAutographed'
      @_hash['isbn'] = 'ISBN'
      @_hash['is_eligible_for_trade_in'] = 'IsEligibleForTradeIn'
      @_hash['is_memorabilia'] = 'IsMemorabilia'
      @_hash['issues_per_year'] = 'IssuesPerYear'
      @_hash['item_dimensions'] = 'ItemDimensions'
      @_hash['item_part_number'] = 'ItemPartNumber'
      @_hash['label'] = 'Label'
      @_hash['languages'] = 'Languages'
      @_hash['legal_disclaimer'] = 'LegalDisclaimer'
      @_hash['list_price'] = 'ListPrice'
      @_hash['magazine_type'] = 'MagazineType'
      @_hash['manufacturer'] = 'Manufacturer'
      @_hash['manufacturer_maximum_age'] = 'ManufacturerMaximumAge'
      @_hash['manufacturer_minimum_age'] = 'ManufacturerMinimumAge'
      @_hash['manufacturer_parts_warranty_description'] = 'ManufacturerPartsWarrantyDescription'
      @_hash['media_type'] = 'MediaType'
      @_hash['model'] = 'Model'
      @_hash['model_year'] = 'ModelYear'
      @_hash['mpn'] = 'MPN'
      @_hash['number_of_discs'] = 'NumberOfDiscs'
      @_hash['number_of_issues'] = 'NumberOfIssues'
      @_hash['number_of_items'] = 'NumberOfItems'
      @_hash['number_of_pages'] = 'NumberOfPages'
      @_hash['number_of_tracks'] = 'NumberOfTracks'
      @_hash['operating_system'] = 'OperatingSystem'
      @_hash['package_dimensions'] = 'PackageDimensions'
      @_hash['package_quantity'] = 'PackageQuantity'
      @_hash['part_number'] = 'PartNumber'
      @_hash['picture_format'] = 'PictureFormat'
      @_hash['platform'] = 'Platform'
      @_hash['product_group'] = 'ProductGroup'
      @_hash['product_type_name'] = 'ProductTypeName'
      @_hash['product_type_subcategory'] = 'ProductTypeSubcategory'
      @_hash['publication_date'] = 'PublicationDate'
      @_hash['publisher'] = 'Publisher'
      @_hash['region_code'] = 'RegionCode'
      @_hash['release_date'] = 'ReleaseDate'
      @_hash['season_sequence'] = 'SeasonSequence'
      @_hash['running_time'] = 'RunningTime'
      @_hash['seikodo_product_code'] = 'SeikodoProductCode'
      @_hash['size'] = 'Size'
      @_hash['sku'] = 'SKU'
      @_hash['studio'] = 'Studio'
      @_hash['subscription_length'] = 'SubscriptionLength'
      @_hash['title'] = 'Title'
      @_hash['track_sequence'] = 'TrackSequence'
      @_hash['trade_in_value'] = 'TradeInValue'
      @_hash['upc'] = 'UPC'
      @_hash['upc_list'] = 'UPCList'
      @_hash['warranty'] = 'Warranty'
      @_hash['weee_tax_value'] = 'WEEETaxValue'
      @_hash
    end

    def initialize(actor = nil,
                   artist = nil,
                   aspect_ratio = nil,
                   audience_rating = nil,
                   audio_format = nil,
                   author = nil,
                   binding = nil,
                   brand = nil,
                   catalog_number_list = nil,
                   category = nil,
                   cero_age_rating = nil,
                   clothing_size = nil,
                   color = nil,
                   creator = nil,
                   department = nil,
                   director = nil,
                   ean = nil,
                   ean_list = nil,
                   edition = nil,
                   eisbn = nil,
                   energy_efficiency_class = nil,
                   episode_sequence = nil,
                   esrb_age_rating = nil,
                   feature = nil,
                   format = nil,
                   genre = nil,
                   hardware_platform = nil,
                   hazardous_material_type = nil,
                   is_adult_product = nil,
                   is_autographed = nil,
                   isbn = nil,
                   is_eligible_for_trade_in = nil,
                   is_memorabilia = nil,
                   issues_per_year = nil,
                   item_dimensions = nil,
                   item_part_number = nil,
                   label = nil,
                   languages = nil,
                   legal_disclaimer = nil,
                   list_price = nil,
                   magazine_type = nil,
                   manufacturer = nil,
                   manufacturer_maximum_age = nil,
                   manufacturer_minimum_age = nil,
                   manufacturer_parts_warranty_description = nil,
                   media_type = nil,
                   model = nil,
                   model_year = nil,
                   mpn = nil,
                   number_of_discs = nil,
                   number_of_issues = nil,
                   number_of_items = nil,
                   number_of_pages = nil,
                   number_of_tracks = nil,
                   operating_system = nil,
                   package_dimensions = nil,
                   package_quantity = nil,
                   part_number = nil,
                   picture_format = nil,
                   platform = nil,
                   product_group = nil,
                   product_type_name = nil,
                   product_type_subcategory = nil,
                   publication_date = nil,
                   publisher = nil,
                   region_code = nil,
                   release_date = nil,
                   season_sequence = nil,
                   running_time = nil,
                   seikodo_product_code = nil,
                   size = nil,
                   sku = nil,
                   studio = nil,
                   subscription_length = nil,
                   title = nil,
                   track_sequence = nil,
                   trade_in_value = nil,
                   upc = nil,
                   upc_list = nil,
                   warranty = nil,
                   weee_tax_value = nil)
      @actor = actor
      @artist = artist
      @aspect_ratio = aspect_ratio
      @audience_rating = audience_rating
      @audio_format = audio_format
      @author = author
      @binding = binding
      @brand = brand
      @catalog_number_list = catalog_number_list
      @category = category
      @cero_age_rating = cero_age_rating
      @clothing_size = clothing_size
      @color = color
      @creator = creator
      @department = department
      @director = director
      @ean = ean
      @ean_list = ean_list
      @edition = edition
      @eisbn = eisbn
      @energy_efficiency_class = energy_efficiency_class
      @episode_sequence = episode_sequence
      @esrb_age_rating = esrb_age_rating
      @feature = feature
      @format = format
      @genre = genre
      @hardware_platform = hardware_platform
      @hazardous_material_type = hazardous_material_type
      @is_adult_product = is_adult_product
      @is_autographed = is_autographed
      @isbn = isbn
      @is_eligible_for_trade_in = is_eligible_for_trade_in
      @is_memorabilia = is_memorabilia
      @issues_per_year = issues_per_year
      @item_dimensions = item_dimensions
      @item_part_number = item_part_number
      @label = label
      @languages = languages
      @legal_disclaimer = legal_disclaimer
      @list_price = list_price
      @magazine_type = magazine_type
      @manufacturer = manufacturer
      @manufacturer_maximum_age = manufacturer_maximum_age
      @manufacturer_minimum_age = manufacturer_minimum_age
      @manufacturer_parts_warranty_description = manufacturer_parts_warranty_description
      @media_type = media_type
      @model = model
      @model_year = model_year
      @mpn = mpn
      @number_of_discs = number_of_discs
      @number_of_issues = number_of_issues
      @number_of_items = number_of_items
      @number_of_pages = number_of_pages
      @number_of_tracks = number_of_tracks
      @operating_system = operating_system
      @package_dimensions = package_dimensions
      @package_quantity = package_quantity
      @part_number = part_number
      @picture_format = picture_format
      @platform = platform
      @product_group = product_group
      @product_type_name = product_type_name
      @product_type_subcategory = product_type_subcategory
      @publication_date = publication_date
      @publisher = publisher
      @region_code = region_code
      @release_date = release_date
      @season_sequence = season_sequence
      @running_time = running_time
      @seikodo_product_code = seikodo_product_code
      @size = size
      @sku = sku
      @studio = studio
      @subscription_length = subscription_length
      @title = title
      @track_sequence = track_sequence
      @trade_in_value = trade_in_value
      @upc = upc
      @upc_list = upc_list
      @warranty = warranty
      @weee_tax_value = weee_tax_value
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      actor = hash['Actor']
      artist = hash['Artist']
      aspect_ratio = hash['AspectRatio']
      audience_rating = hash['AudienceRating']
      audio_format = hash['AudioFormat']
      author = hash['Author']
      binding = hash['Binding']
      brand = hash['Brand']
      catalog_number_list = CatalogNumberList.from_hash(hash['CatalogNumberList']) if
        hash['CatalogNumberList']
      category = hash['Category']
      cero_age_rating = hash['CEROAgeRating']
      clothing_size = hash['ClothingSize']
      color = hash['Color']
      # Parameter is an array, so we need to iterate through it
      creator = nil
      unless hash['Creator'].nil?
        creator = []
        hash['Creator'].each do |structure|
          creator << (Creator.from_hash(structure) if structure)
        end
      end
      department = hash['Department']
      director = hash['Director']
      ean = hash['EAN']
      ean_list = EANList.from_hash(hash['EANList']) if hash['EANList']
      edition = hash['Edition']
      eisbn = hash['EISBN']
      energy_efficiency_class = hash['EnergyEfficiencyClass']
      episode_sequence = hash['EpisodeSequence']
      esrb_age_rating = hash['ESRBAgeRating']
      feature = hash['Feature']
      format = hash['Format']
      genre = hash['Genre']
      hardware_platform = hash['HardwarePlatform']
      hazardous_material_type = hash['HazardousMaterialType']
      is_adult_product = hash['IsAdultProduct']
      is_autographed = hash['IsAutographed']
      isbn = hash['ISBN']
      is_eligible_for_trade_in = hash['IsEligibleForTradeIn']
      is_memorabilia = hash['IsMemorabilia']
      issues_per_year = hash['IssuesPerYear']
      item_dimensions = ItemDimensions.from_hash(hash['ItemDimensions']) if
        hash['ItemDimensions']
      item_part_number = hash['ItemPartNumber']
      label = hash['Label']
      languages = Languages.from_hash(hash['Languages']) if hash['Languages']
      legal_disclaimer = hash['LegalDisclaimer']
      list_price = Price.from_hash(hash['ListPrice']) if hash['ListPrice']
      magazine_type = hash['MagazineType']
      manufacturer = hash['Manufacturer']
      manufacturer_maximum_age = DecimalWithUnits.from_hash(hash['ManufacturerMaximumAge']) if
        hash['ManufacturerMaximumAge']
      manufacturer_minimum_age = DecimalWithUnits.from_hash(hash['ManufacturerMinimumAge']) if
        hash['ManufacturerMinimumAge']
      manufacturer_parts_warranty_description = hash['ManufacturerPartsWarrantyDescription']
      media_type = hash['MediaType']
      model = hash['Model']
      model_year = hash['ModelYear']
      mpn = hash['MPN']
      number_of_discs = hash['NumberOfDiscs']
      number_of_issues = hash['NumberOfIssues']
      number_of_items = hash['NumberOfItems']
      number_of_pages = hash['NumberOfPages']
      number_of_tracks = hash['NumberOfTracks']
      operating_system = hash['OperatingSystem']
      package_dimensions = PackageDimensions.from_hash(hash['PackageDimensions']) if
        hash['PackageDimensions']
      package_quantity = hash['PackageQuantity']
      part_number = hash['PartNumber']
      picture_format = hash['PictureFormat']
      platform = hash['Platform']
      product_group = hash['ProductGroup']
      product_type_name = hash['ProductTypeName']
      product_type_subcategory = hash['ProductTypeSubcategory']
      publication_date = hash['PublicationDate']
      publisher = hash['Publisher']
      region_code = hash['RegionCode']
      release_date = hash['ReleaseDate']
      season_sequence = hash['SeasonSequence']
      running_time = DecimalWithUnits.from_hash(hash['RunningTime']) if
        hash['RunningTime']
      seikodo_product_code = hash['SeikodoProductCode']
      size = hash['Size']
      sku = hash['SKU']
      studio = hash['Studio']
      subscription_length = NonNegativeIntegerWithUnits.from_hash(hash['SubscriptionLength']) if
        hash['SubscriptionLength']
      title = hash['Title']
      track_sequence = hash['TrackSequence']
      trade_in_value = Price.from_hash(hash['TradeInValue']) if
        hash['TradeInValue']
      upc = hash['UPC']
      upc_list = UPCList.from_hash(hash['UPCList']) if hash['UPCList']
      warranty = hash['Warranty']
      weee_tax_value = Price.from_hash(hash['WEEETaxValue']) if
        hash['WEEETaxValue']

      # Create object from extracted values.
      ItemAttributes.new(actor,
                         artist,
                         aspect_ratio,
                         audience_rating,
                         audio_format,
                         author,
                         binding,
                         brand,
                         catalog_number_list,
                         category,
                         cero_age_rating,
                         clothing_size,
                         color,
                         creator,
                         department,
                         director,
                         ean,
                         ean_list,
                         edition,
                         eisbn,
                         energy_efficiency_class,
                         episode_sequence,
                         esrb_age_rating,
                         feature,
                         format,
                         genre,
                         hardware_platform,
                         hazardous_material_type,
                         is_adult_product,
                         is_autographed,
                         isbn,
                         is_eligible_for_trade_in,
                         is_memorabilia,
                         issues_per_year,
                         item_dimensions,
                         item_part_number,
                         label,
                         languages,
                         legal_disclaimer,
                         list_price,
                         magazine_type,
                         manufacturer,
                         manufacturer_maximum_age,
                         manufacturer_minimum_age,
                         manufacturer_parts_warranty_description,
                         media_type,
                         model,
                         model_year,
                         mpn,
                         number_of_discs,
                         number_of_issues,
                         number_of_items,
                         number_of_pages,
                         number_of_tracks,
                         operating_system,
                         package_dimensions,
                         package_quantity,
                         part_number,
                         picture_format,
                         platform,
                         product_group,
                         product_type_name,
                         product_type_subcategory,
                         publication_date,
                         publisher,
                         region_code,
                         release_date,
                         season_sequence,
                         running_time,
                         seikodo_product_code,
                         size,
                         sku,
                         studio,
                         subscription_length,
                         title,
                         track_sequence,
                         trade_in_value,
                         upc,
                         upc_list,
                         warranty,
                         weee_tax_value)
    end
  end
end
