# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # ItemDimensions Model.
  class ItemDimensions < BaseModel
    # TODO: Write general description for this method
    # @return [DecimalWithUnits]
    attr_accessor :height

    # TODO: Write general description for this method
    # @return [DecimalWithUnits]
    attr_accessor :length

    # TODO: Write general description for this method
    # @return [DecimalWithUnits]
    attr_accessor :weight

    # TODO: Write general description for this method
    # @return [DecimalWithUnits]
    attr_accessor :width

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['height'] = 'Height'
      @_hash['length'] = 'Length'
      @_hash['weight'] = 'Weight'
      @_hash['width'] = 'Width'
      @_hash
    end

    def initialize(height = nil,
                   length = nil,
                   weight = nil,
                   width = nil)
      @height = height
      @length = length
      @weight = weight
      @width = width
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      height = DecimalWithUnits.from_hash(hash['Height']) if hash['Height']
      length = DecimalWithUnits.from_hash(hash['Length']) if hash['Length']
      weight = DecimalWithUnits.from_hash(hash['Weight']) if hash['Weight']
      width = DecimalWithUnits.from_hash(hash['Width']) if hash['Width']

      # Create object from extracted values.
      ItemDimensions.new(height,
                         length,
                         weight,
                         width)
    end
  end
end
