# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Item23 Model.
  class Item23 < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :asin

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :offer_listing_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :quantity

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :associate_tag

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :list_item_id

    # TODO: Write general description for this method
    # @return [List of MetaData]
    attr_accessor :meta_data

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['asin'] = 'ASIN'
      @_hash['offer_listing_id'] = 'OfferListingId'
      @_hash['quantity'] = 'Quantity'
      @_hash['associate_tag'] = 'AssociateTag'
      @_hash['list_item_id'] = 'ListItemId'
      @_hash['meta_data'] = 'MetaData'
      @_hash
    end

    def initialize(asin = nil,
                   offer_listing_id = nil,
                   quantity = nil,
                   associate_tag = nil,
                   list_item_id = nil,
                   meta_data = nil)
      @asin = asin
      @offer_listing_id = offer_listing_id
      @quantity = quantity
      @associate_tag = associate_tag
      @list_item_id = list_item_id
      @meta_data = meta_data
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      asin = hash['ASIN']
      offer_listing_id = hash['OfferListingId']
      quantity = hash['Quantity']
      associate_tag = hash['AssociateTag']
      list_item_id = hash['ListItemId']
      # Parameter is an array, so we need to iterate through it
      meta_data = nil
      unless hash['MetaData'].nil?
        meta_data = []
        hash['MetaData'].each do |structure|
          meta_data << (MetaData.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      Item23.new(asin,
                 offer_listing_id,
                 quantity,
                 associate_tag,
                 list_item_id,
                 meta_data)
    end
  end
end
