# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # ItemLinks Model.
  class ItemLinks < BaseModel
    # TODO: Write general description for this method
    # @return [List of ItemLink]
    attr_accessor :item_link

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['item_link'] = 'ItemLink'
      @_hash
    end

    def initialize(item_link = nil)
      @item_link = item_link
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      item_link = nil
      unless hash['ItemLink'].nil?
        item_link = []
        hash['ItemLink'].each do |structure|
          item_link << (ItemLink.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      ItemLinks.new(item_link)
    end
  end
end
