# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # ItemLink Model.
  class ItemLink < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :description

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['description'] = 'Description'
      @_hash['url'] = 'URL'
      @_hash
    end

    def initialize(description = nil,
                   url = nil)
      @description = description
      @url = url
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      description = hash['Description']
      url = hash['URL']

      # Create object from extracted values.
      ItemLink.new(description,
                   url)
    end
  end
end
