# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Language Model.
  class Language < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :audio_format

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'Name'
      @_hash['type'] = 'Type'
      @_hash['audio_format'] = 'AudioFormat'
      @_hash
    end

    def initialize(name = nil,
                   type = nil,
                   audio_format = nil)
      @name = name
      @type = type
      @audio_format = audio_format
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash['Name']
      type = hash['Type']
      audio_format = hash['AudioFormat']

      # Create object from extracted values.
      Language.new(name,
                   type,
                   audio_format)
    end
  end
end
