# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Languages Model.
  class Languages < BaseModel
    # TODO: Write general description for this method
    # @return [List of Language]
    attr_accessor :language

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['language'] = 'Language'
      @_hash
    end

    def initialize(language = nil)
      @language = language
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      language = nil
      unless hash['Language'].nil?
        language = []
        hash['Language'].each do |structure|
          language << (Language.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      Languages.new(language)
    end
  end
end
