# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # LoyaltyPoints Model.
  class LoyaltyPoints < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :points

    # TODO: Write general description for this method
    # @return [Price]
    attr_accessor :typical_redemption_value

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['points'] = 'Points'
      @_hash['typical_redemption_value'] = 'TypicalRedemptionValue'
      @_hash
    end

    def initialize(points = nil,
                   typical_redemption_value = nil)
      @points = points
      @typical_redemption_value = typical_redemption_value
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      points = hash['Points']
      typical_redemption_value = Price.from_hash(hash['TypicalRedemptionValue']) if
        hash['TypicalRedemptionValue']

      # Create object from extracted values.
      LoyaltyPoints.new(points,
                        typical_redemption_value)
    end
  end
end
