# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # MetaData Model.
  class MetaData < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :key

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :value

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['key'] = 'Key'
      @_hash['value'] = 'Value'
      @_hash
    end

    def initialize(key = nil,
                   value = nil)
      @key = key
      @value = value
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      key = hash['Key']
      value = hash['Value']

      # Create object from extracted values.
      MetaData.new(key,
                   value)
    end
  end
end
