# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # MetaData164 Model.
  class MetaData164 < BaseModel
    # TODO: Write general description for this method
    # @return [List of KeyValuePair]
    attr_accessor :key_value_pair

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['key_value_pair'] = 'KeyValuePair'
      @_hash
    end

    def initialize(key_value_pair = nil)
      @key_value_pair = key_value_pair
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      key_value_pair = nil
      unless hash['KeyValuePair'].nil?
        key_value_pair = []
        hash['KeyValuePair'].each do |structure|
          key_value_pair << (KeyValuePair.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      MetaData164.new(key_value_pair)
    end
  end
end
