# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # NewReleases Model.
  class NewReleases < BaseModel
    # TODO: Write general description for this method
    # @return [List of NewRelease]
    attr_accessor :new_release

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['new_release'] = 'NewRelease'
      @_hash
    end

    def initialize(new_release = nil)
      @new_release = new_release
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      new_release = nil
      unless hash['NewRelease'].nil?
        new_release = []
        hash['NewRelease'].each do |structure|
          new_release << (NewRelease.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      NewReleases.new(new_release)
    end
  end
end
