# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # NonNegativeIntegerWithUnits Model.
  class NonNegativeIntegerWithUnits < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :units

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['units'] = 'Units'
      @_hash
    end

    def initialize(units = nil)
      @units = units
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      units = hash['Units']

      # Create object from extracted values.
      NonNegativeIntegerWithUnits.new(units)
    end
  end
end
