# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # OfferAttributes Model.
  class OfferAttributes < BaseModel
    # TODO: Write general description for this method
    # @return [ConditionEnum]
    attr_accessor :condition

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['condition'] = 'Condition'
      @_hash
    end

    def initialize(condition = nil)
      @condition = condition
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      condition = hash['Condition']

      # Create object from extracted values.
      OfferAttributes.new(condition)
    end
  end
end
