# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Offers Model.
  class Offers < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :total_offers

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :total_offer_pages

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :more_offers_url

    # TODO: Write general description for this method
    # @return [List of Offer]
    attr_accessor :offer

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['total_offers'] = 'TotalOffers'
      @_hash['total_offer_pages'] = 'TotalOfferPages'
      @_hash['more_offers_url'] = 'MoreOffersUrl'
      @_hash['offer'] = 'Offer'
      @_hash
    end

    def initialize(total_offers = nil,
                   total_offer_pages = nil,
                   more_offers_url = nil,
                   offer = nil)
      @total_offers = total_offers
      @total_offer_pages = total_offer_pages
      @more_offers_url = more_offers_url
      @offer = offer
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      total_offers = hash['TotalOffers']
      total_offer_pages = hash['TotalOfferPages']
      more_offers_url = hash['MoreOffersUrl']
      # Parameter is an array, so we need to iterate through it
      offer = nil
      unless hash['Offer'].nil?
        offer = []
        hash['Offer'].each do |structure|
          offer << (Offer.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      Offers.new(total_offers,
                 total_offer_pages,
                 more_offers_url,
                 offer)
    end
  end
end
