# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # OtherCategoriesSimilarProducts Model.
  class OtherCategoriesSimilarProducts < BaseModel
    # TODO: Write general description for this method
    # @return [List of OtherCategoriesSimilarProduct]
    attr_accessor :other_categories_similar_product

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['other_categories_similar_product'] = 'OtherCategoriesSimilarProduct'
      @_hash
    end

    def initialize(other_categories_similar_product = nil)
      @other_categories_similar_product = other_categories_similar_product
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      other_categories_similar_product = nil
      unless hash['OtherCategoriesSimilarProduct'].nil?
        other_categories_similar_product = []
        hash['OtherCategoriesSimilarProduct'].each do |structure|
          other_categories_similar_product << (OtherCategoriesSimilarProduct.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      OtherCategoriesSimilarProducts.new(other_categories_similar_product)
    end
  end
end
