# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # positiveIntegerOrAll.
  class PositiveIntegerOrAllEnum
    POSITIVE_INTEGER_OR_ALL_ENUM = [
      # TODO: Write general description for ALL
      ALL = 'All'.freeze
    ].freeze
  end
end
