# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Price Model.
  class Price < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :formatted_price

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :amount

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :currency_code

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['formatted_price'] = 'FormattedPrice'
      @_hash['amount'] = 'Amount'
      @_hash['currency_code'] = 'CurrencyCode'
      @_hash
    end

    def initialize(formatted_price = nil,
                   amount = nil,
                   currency_code = nil)
      @formatted_price = formatted_price
      @amount = amount
      @currency_code = currency_code
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      formatted_price = hash['FormattedPrice']
      amount = hash['Amount']
      currency_code = hash['CurrencyCode']

      # Create object from extracted values.
      Price.new(formatted_price,
                amount,
                currency_code)
    end
  end
end
