# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Promotions Model.
  class Promotions < BaseModel
    # TODO: Write general description for this method
    # @return [List of Promotion]
    attr_accessor :promotion

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['promotion'] = 'Promotion'
      @_hash
    end

    def initialize(promotion = nil)
      @promotion = promotion
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      promotion = nil
      unless hash['Promotion'].nil?
        promotion = []
        hash['Promotion'].each do |structure|
          promotion << (Promotion.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      Promotions.new(promotion)
    end
  end
end
