# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Properties Model.
  class Properties < BaseModel
    # TODO: Write general description for this method
    # @return [List of Property]
    attr_accessor :property

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['property'] = 'Property'
      @_hash
    end

    def initialize(property = nil)
      @property = property
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      property = nil
      unless hash['Property'].nil?
        property = []
        hash['Property'].each do |structure|
          property << (Property.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      Properties.new(property)
    end
  end
end
