# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # RelatedItem Model.
  class RelatedItem < BaseModel
    # TODO: Write general description for this method
    # @return [Item]
    attr_accessor :item

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['item'] = 'Item'
      @_hash
    end

    def initialize(item = nil)
      @item = item
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      item = Item.from_hash(hash['Item']) if hash['Item']

      # Create object from extracted values.
      RelatedItem.new(item)
    end
  end
end
