# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Relationship.
  class RelationshipEnum
    RELATIONSHIP_ENUM = [
      # TODO: Write general description for PARENTS
      PARENTS = 'Parents'.freeze,

      # TODO: Write general description for CHILDREN
      CHILDREN = 'Children'.freeze
    ].freeze
  end
end
