# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # RelatedItems265 Model.
  class RelatedItems265 < BaseModel
    # TODO: Write general description for this method
    # @return [RelationshipEnum]
    attr_accessor :relationship

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :relationship_type

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :related_item_count

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :related_item_page_count

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :related_item_page

    # TODO: Write general description for this method
    # @return [List of RelatedItem264]
    attr_accessor :related_item

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['relationship'] = 'Relationship'
      @_hash['relationship_type'] = 'RelationshipType'
      @_hash['related_item_count'] = 'RelatedItemCount'
      @_hash['related_item_page_count'] = 'RelatedItemPageCount'
      @_hash['related_item_page'] = 'RelatedItemPage'
      @_hash['related_item'] = 'RelatedItem'
      @_hash
    end

    def initialize(relationship = nil,
                   relationship_type = nil,
                   related_item_count = nil,
                   related_item_page_count = nil,
                   related_item_page = nil,
                   related_item = nil)
      @relationship = relationship
      @relationship_type = relationship_type
      @related_item_count = related_item_count
      @related_item_page_count = related_item_page_count
      @related_item_page = related_item_page
      @related_item = related_item
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      relationship = hash['Relationship']
      relationship_type = hash['RelationshipType']
      related_item_count = hash['RelatedItemCount']
      related_item_page_count = hash['RelatedItemPageCount']
      related_item_page = hash['RelatedItemPage']
      # Parameter is an array, so we need to iterate through it
      related_item = nil
      unless hash['RelatedItem'].nil?
        related_item = []
        hash['RelatedItem'].each do |structure|
          related_item << (RelatedItem264.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      RelatedItems265.new(relationship,
                          relationship_type,
                          related_item_count,
                          related_item_page_count,
                          related_item_page,
                          related_item)
    end
  end
end
