# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # RentalOffer Model.
  class RentalOffer < BaseModel
    # TODO: Write general description for this method
    # @return [Merchant]
    attr_accessor :merchant

    # TODO: Write general description for this method
    # @return [List of RentalListing]
    attr_accessor :rental_listing

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['merchant'] = 'Merchant'
      @_hash['rental_listing'] = 'RentalListing'
      @_hash
    end

    def initialize(merchant = nil,
                   rental_listing = nil)
      @merchant = merchant
      @rental_listing = rental_listing
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      merchant = Merchant.from_hash(hash['Merchant']) if hash['Merchant']
      # Parameter is an array, so we need to iterate through it
      rental_listing = nil
      unless hash['RentalListing'].nil?
        rental_listing = []
        hash['RentalListing'].each do |structure|
          rental_listing << (RentalListing.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      RentalOffer.new(merchant,
                      rental_listing)
    end
  end
end
