# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # RentalOffers Model.
  class RentalOffers < BaseModel
    # TODO: Write general description for this method
    # @return [List of RentalOffer]
    attr_accessor :rental_offer

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['rental_offer'] = 'RentalOffer'
      @_hash
    end

    def initialize(rental_offer = nil)
      @rental_offer = rental_offer
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      rental_offer = nil
      unless hash['RentalOffer'].nil?
        rental_offer = []
        hash['RentalOffer'].each do |structure|
          rental_offer << (RentalOffer.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      RentalOffers.new(rental_offer)
    end
  end
end
