# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Request Model.
  class Request < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :is_valid

    # TODO: Write general description for this method
    # @return [BrowseNodeLookupRequest]
    attr_accessor :browse_node_lookup_request

    # TODO: Write general description for this method
    # @return [ItemSearchRequest]
    attr_accessor :item_search_request

    # TODO: Write general description for this method
    # @return [ItemLookupRequest]
    attr_accessor :item_lookup_request

    # TODO: Write general description for this method
    # @return [SimilarityLookupRequest]
    attr_accessor :similarity_lookup_request

    # TODO: Write general description for this method
    # @return [CartGetRequest]
    attr_accessor :cart_get_request

    # TODO: Write general description for this method
    # @return [CartAddRequest]
    attr_accessor :cart_add_request

    # TODO: Write general description for this method
    # @return [CartCreateRequest55]
    attr_accessor :cart_create_request

    # TODO: Write general description for this method
    # @return [CartModifyRequest56]
    attr_accessor :cart_modify_request

    # TODO: Write general description for this method
    # @return [CartClearRequest]
    attr_accessor :cart_clear_request

    # TODO: Write general description for this method
    # @return [Errors]
    attr_accessor :errors

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['is_valid'] = 'IsValid'
      @_hash['browse_node_lookup_request'] = 'BrowseNodeLookupRequest'
      @_hash['item_search_request'] = 'ItemSearchRequest'
      @_hash['item_lookup_request'] = 'ItemLookupRequest'
      @_hash['similarity_lookup_request'] = 'SimilarityLookupRequest'
      @_hash['cart_get_request'] = 'CartGetRequest'
      @_hash['cart_add_request'] = 'CartAddRequest'
      @_hash['cart_create_request'] = 'CartCreateRequest'
      @_hash['cart_modify_request'] = 'CartModifyRequest'
      @_hash['cart_clear_request'] = 'CartClearRequest'
      @_hash['errors'] = 'Errors'
      @_hash
    end

    def initialize(is_valid = nil,
                   browse_node_lookup_request = nil,
                   item_search_request = nil,
                   item_lookup_request = nil,
                   similarity_lookup_request = nil,
                   cart_get_request = nil,
                   cart_add_request = nil,
                   cart_create_request = nil,
                   cart_modify_request = nil,
                   cart_clear_request = nil,
                   errors = nil)
      @is_valid = is_valid
      @browse_node_lookup_request = browse_node_lookup_request
      @item_search_request = item_search_request
      @item_lookup_request = item_lookup_request
      @similarity_lookup_request = similarity_lookup_request
      @cart_get_request = cart_get_request
      @cart_add_request = cart_add_request
      @cart_create_request = cart_create_request
      @cart_modify_request = cart_modify_request
      @cart_clear_request = cart_clear_request
      @errors = errors
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      is_valid = hash['IsValid']
      browse_node_lookup_request = BrowseNodeLookupRequest.from_hash(hash['BrowseNodeLookupRequest']) if
        hash['BrowseNodeLookupRequest']
      item_search_request = ItemSearchRequest.from_hash(hash['ItemSearchRequest']) if
        hash['ItemSearchRequest']
      item_lookup_request = ItemLookupRequest.from_hash(hash['ItemLookupRequest']) if
        hash['ItemLookupRequest']
      similarity_lookup_request = SimilarityLookupRequest.from_hash(hash['SimilarityLookupRequest']) if
        hash['SimilarityLookupRequest']
      cart_get_request = CartGetRequest.from_hash(hash['CartGetRequest']) if
        hash['CartGetRequest']
      cart_add_request = CartAddRequest.from_hash(hash['CartAddRequest']) if
        hash['CartAddRequest']
      cart_create_request = CartCreateRequest55.from_hash(hash['CartCreateRequest']) if
        hash['CartCreateRequest']
      cart_modify_request = CartModifyRequest56.from_hash(hash['CartModifyRequest']) if
        hash['CartModifyRequest']
      cart_clear_request = CartClearRequest.from_hash(hash['CartClearRequest']) if
        hash['CartClearRequest']
      errors = Errors.from_hash(hash['Errors']) if hash['Errors']

      # Create object from extracted values.
      Request.new(is_valid,
                  browse_node_lookup_request,
                  item_search_request,
                  item_lookup_request,
                  similarity_lookup_request,
                  cart_get_request,
                  cart_add_request,
                  cart_create_request,
                  cart_modify_request,
                  cart_clear_request,
                  errors)
    end
  end
end
