# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # SavedForLaterItems Model.
  class SavedForLaterItems < BaseModel
    # TODO: Write general description for this method
    # @return [List of CartItem]
    attr_accessor :saved_for_later_item

    # TODO: Write general description for this method
    # @return [Price]
    attr_accessor :sub_total

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['saved_for_later_item'] = 'SavedForLaterItem'
      @_hash['sub_total'] = 'SubTotal'
      @_hash
    end

    def initialize(saved_for_later_item = nil,
                   sub_total = nil)
      @saved_for_later_item = saved_for_later_item
      @sub_total = sub_total
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      saved_for_later_item = nil
      unless hash['SavedForLaterItem'].nil?
        saved_for_later_item = []
        hash['SavedForLaterItem'].each do |structure|
          saved_for_later_item << (CartItem.from_hash(structure) if structure)
        end
      end
      sub_total = Price.from_hash(hash['SubTotal']) if hash['SubTotal']

      # Create object from extracted values.
      SavedForLaterItems.new(saved_for_later_item,
                             sub_total)
    end
  end
end
