# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # SearchIndex Model.
  class SearchIndex < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :index_name

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :relevance_rank

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :asin

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :results

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :pages

    # TODO: Write general description for this method
    # @return [CorrectedQuery]
    attr_accessor :corrected_query

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['index_name'] = 'IndexName'
      @_hash['relevance_rank'] = 'RelevanceRank'
      @_hash['asin'] = 'ASIN'
      @_hash['results'] = 'Results'
      @_hash['pages'] = 'Pages'
      @_hash['corrected_query'] = 'CorrectedQuery'
      @_hash
    end

    def initialize(index_name = nil,
                   relevance_rank = nil,
                   asin = nil,
                   results = nil,
                   pages = nil,
                   corrected_query = nil)
      @index_name = index_name
      @relevance_rank = relevance_rank
      @asin = asin
      @results = results
      @pages = pages
      @corrected_query = corrected_query
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      index_name = hash['IndexName']
      relevance_rank = hash['RelevanceRank']
      asin = hash['ASIN']
      results = hash['Results']
      pages = hash['Pages']
      corrected_query = CorrectedQuery.from_hash(hash['CorrectedQuery']) if
        hash['CorrectedQuery']

      # Create object from extracted values.
      SearchIndex.new(index_name,
                      relevance_rank,
                      asin,
                      results,
                      pages,
                      corrected_query)
    end
  end
end
