# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # SearchBinSet Model.
  class SearchBinSet < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :narrow_by

    # TODO: Write general description for this method
    # @return [List of Bin]
    attr_accessor :bin

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['narrow_by'] = 'NarrowBy'
      @_hash['bin'] = 'Bin'
      @_hash
    end

    def initialize(narrow_by = nil,
                   bin = nil)
      @narrow_by = narrow_by
      @bin = bin
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      narrow_by = hash['NarrowBy']
      # Parameter is an array, so we need to iterate through it
      bin = nil
      unless hash['Bin'].nil?
        bin = []
        hash['Bin'].each do |structure|
          bin << (Bin.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      SearchBinSet.new(narrow_by,
                       bin)
    end
  end
end
