# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # SearchBinSets Model.
  class SearchBinSets < BaseModel
    # TODO: Write general description for this method
    # @return [List of SearchBinSet]
    attr_accessor :search_bin_set

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['search_bin_set'] = 'SearchBinSet'
      @_hash
    end

    def initialize(search_bin_set = nil)
      @search_bin_set = search_bin_set
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      search_bin_set = nil
      unless hash['SearchBinSet'].nil?
        search_bin_set = []
        hash['SearchBinSet'].each do |structure|
          search_bin_set << (SearchBinSet.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      SearchBinSets.new(search_bin_set)
    end
  end
end
