# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # SimilarityLookupRequest Model.
  class SimilarityLookupRequest < BaseModel
    # TODO: Write general description for this method
    # @return [ConditionEnum]
    attr_accessor :condition

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :item_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :merchant_id

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :response_group

    # TODO: Write general description for this method
    # @return [SimilarityTypeEnum]
    attr_accessor :similarity_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['condition'] = 'Condition'
      @_hash['item_id'] = 'ItemId'
      @_hash['merchant_id'] = 'MerchantId'
      @_hash['response_group'] = 'ResponseGroup'
      @_hash['similarity_type'] = 'SimilarityType'
      @_hash
    end

    def initialize(condition = nil,
                   item_id = nil,
                   merchant_id = nil,
                   response_group = nil,
                   similarity_type = nil)
      @condition = condition
      @item_id = item_id
      @merchant_id = merchant_id
      @response_group = response_group
      @similarity_type = similarity_type
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      condition = hash['Condition']
      item_id = hash['ItemId']
      merchant_id = hash['MerchantId']
      response_group = hash['ResponseGroup']
      similarity_type = hash['SimilarityType']

      # Create object from extracted values.
      SimilarityLookupRequest.new(condition,
                                  item_id,
                                  merchant_id,
                                  response_group,
                                  similarity_type)
    end
  end
end
