# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # SimilarityType.
  class SimilarityTypeEnum
    SIMILARITY_TYPE_ENUM = [
      # TODO: Write general description for INTERSECTION
      INTERSECTION = 'Intersection'.freeze,

      # TODO: Write general description for RANDOM
      RANDOM = 'Random'.freeze
    ].freeze
  end
end
