# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # SimilarProducts Model.
  class SimilarProducts < BaseModel
    # TODO: Write general description for this method
    # @return [List of SimilarProduct]
    attr_accessor :similar_product

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['similar_product'] = 'SimilarProduct'
      @_hash
    end

    def initialize(similar_product = nil)
      @similar_product = similar_product
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      similar_product = nil
      unless hash['SimilarProduct'].nil?
        similar_product = []
        hash['SimilarProduct'].each do |structure|
          similar_product << (SimilarProduct.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      SimilarProducts.new(similar_product)
    end
  end
end
