# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # SimilarViewedProducts Model.
  class SimilarViewedProducts < BaseModel
    # TODO: Write general description for this method
    # @return [List of SimilarViewedProduct]
    attr_accessor :similar_viewed_product

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['similar_viewed_product'] = 'SimilarViewedProduct'
      @_hash
    end

    def initialize(similar_viewed_product = nil)
      @similar_viewed_product = similar_viewed_product
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      similar_viewed_product = nil
      unless hash['SimilarViewedProduct'].nil?
        similar_viewed_product = []
        hash['SimilarViewedProduct'].each do |structure|
          similar_viewed_product << (SimilarViewedProduct.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      SimilarViewedProducts.new(similar_viewed_product)
    end
  end
end
