# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Summary Model.
  class Summary < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :promotion_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :message

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :category

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :start_date

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :end_date

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :eligibility_requirement_description

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :benefit_description

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :terms_and_conditions

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['promotion_id'] = 'PromotionId'
      @_hash['message'] = 'Message'
      @_hash['category'] = 'Category'
      @_hash['start_date'] = 'StartDate'
      @_hash['end_date'] = 'EndDate'
      @_hash['eligibility_requirement_description'] = 'EligibilityRequirementDescription'
      @_hash['benefit_description'] = 'BenefitDescription'
      @_hash['terms_and_conditions'] = 'TermsAndConditions'
      @_hash
    end

    def initialize(promotion_id = nil,
                   message = nil,
                   category = nil,
                   start_date = nil,
                   end_date = nil,
                   eligibility_requirement_description = nil,
                   benefit_description = nil,
                   terms_and_conditions = nil)
      @promotion_id = promotion_id
      @message = message
      @category = category
      @start_date = start_date
      @end_date = end_date
      @eligibility_requirement_description = eligibility_requirement_description
      @benefit_description = benefit_description
      @terms_and_conditions = terms_and_conditions
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      promotion_id = hash['PromotionId']
      message = hash['Message']
      category = hash['Category']
      start_date = hash['StartDate']
      end_date = hash['EndDate']
      eligibility_requirement_description = hash['EligibilityRequirementDescription']
      benefit_description = hash['BenefitDescription']
      terms_and_conditions = hash['TermsAndConditions']

      # Create object from extracted values.
      Summary.new(promotion_id,
                  message,
                  category,
                  start_date,
                  end_date,
                  eligibility_requirement_description,
                  benefit_description,
                  terms_and_conditions)
    end
  end
end
