# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # TopSellers Model.
  class TopSellers < BaseModel
    # TODO: Write general description for this method
    # @return [List of TopSeller]
    attr_accessor :top_seller

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['top_seller'] = 'TopSeller'
      @_hash
    end

    def initialize(top_seller = nil)
      @top_seller = top_seller
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      top_seller = nil
      unless hash['TopSeller'].nil?
        top_seller = []
        hash['TopSeller'].each do |structure|
          top_seller << (TopSeller.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      TopSellers.new(top_seller)
    end
  end
end
