# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # TopItemSet Model.
  class TopItemSet < BaseModel
    # TODO: Write general description for this method
    # @return [List of TopItem]
    attr_accessor :top_item

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['top_item'] = 'TopItem'
      @_hash['type'] = 'Type'
      @_hash
    end

    def initialize(top_item = nil,
                   type = nil)
      @top_item = top_item
      @type = type
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      top_item = nil
      unless hash['TopItem'].nil?
        top_item = []
        hash['TopItem'].each do |structure|
          top_item << (TopItem.from_hash(structure) if structure)
        end
      end
      type = hash['Type']

      # Create object from extracted values.
      TopItemSet.new(top_item,
                     type)
    end
  end
end
