# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # TopSeller Model.
  class TopSeller < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :asin

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :title

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['asin'] = 'ASIN'
      @_hash['title'] = 'Title'
      @_hash
    end

    def initialize(asin = nil,
                   title = nil)
      @asin = asin
      @title = title
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      asin = hash['ASIN']
      title = hash['Title']

      # Create object from extracted values.
      TopSeller.new(asin,
                    title)
    end
  end
end
