# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # TopItem Model.
  class TopItem < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :asin

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :title

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :detail_page_url

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :product_group

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :author

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :artist

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :actor

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['asin'] = 'ASIN'
      @_hash['title'] = 'Title'
      @_hash['detail_page_url'] = 'DetailPageURL'
      @_hash['product_group'] = 'ProductGroup'
      @_hash['author'] = 'Author'
      @_hash['artist'] = 'Artist'
      @_hash['actor'] = 'Actor'
      @_hash
    end

    def initialize(asin = nil,
                   title = nil,
                   detail_page_url = nil,
                   product_group = nil,
                   author = nil,
                   artist = nil,
                   actor = nil)
      @asin = asin
      @title = title
      @detail_page_url = detail_page_url
      @product_group = product_group
      @author = author
      @artist = artist
      @actor = actor
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      asin = hash['ASIN']
      title = hash['Title']
      detail_page_url = hash['DetailPageURL']
      product_group = hash['ProductGroup']
      author = hash['Author']
      artist = hash['Artist']
      actor = hash['Actor']

      # Create object from extracted values.
      TopItem.new(asin,
                  title,
                  detail_page_url,
                  product_group,
                  author,
                  artist,
                  actor)
    end
  end
end
