# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Track Model.
  class Track < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :number

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['number'] = 'Number'
      @_hash
    end

    def initialize(number = nil)
      @number = number
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      number = hash['Number']

      # Create object from extracted values.
      Track.new(number)
    end
  end
end
