# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # UPCList Model.
  class UPCList < BaseModel
    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :upc_list_element

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['upc_list_element'] = 'UPCListElement'
      @_hash
    end

    def initialize(upc_list_element = nil)
      @upc_list_element = upc_list_element
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      upc_list_element = hash['UPCListElement']

      # Create object from extracted values.
      UPCList.new(upc_list_element)
    end
  end
end
