# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # Variations Model.
  class Variations < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :total_variations

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :total_variation_pages

    # TODO: Write general description for this method
    # @return [VariationDimensions]
    attr_accessor :variation_dimensions

    # TODO: Write general description for this method
    # @return [List of Item]
    attr_accessor :item

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['total_variations'] = 'TotalVariations'
      @_hash['total_variation_pages'] = 'TotalVariationPages'
      @_hash['variation_dimensions'] = 'VariationDimensions'
      @_hash['item'] = 'Item'
      @_hash
    end

    def initialize(total_variations = nil,
                   total_variation_pages = nil,
                   variation_dimensions = nil,
                   item = nil)
      @total_variations = total_variations
      @total_variation_pages = total_variation_pages
      @variation_dimensions = variation_dimensions
      @item = item
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      total_variations = hash['TotalVariations']
      total_variation_pages = hash['TotalVariationPages']
      variation_dimensions = VariationDimensions.from_hash(hash['VariationDimensions']) if
        hash['VariationDimensions']
      # Parameter is an array, so we need to iterate through it
      item = nil
      unless hash['Item'].nil?
        item = []
        hash['Item'].each do |structure|
          item << (Item.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      Variations.new(total_variations,
                     total_variation_pages,
                     variation_dimensions,
                     item)
    end
  end
end
