# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # VariationDimensions Model.
  class VariationDimensions < BaseModel
    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :variation_dimension

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['variation_dimension'] = 'VariationDimension'
      @_hash
    end

    def initialize(variation_dimension = nil)
      @variation_dimension = variation_dimension
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      variation_dimension = hash['VariationDimension']

      # Create object from extracted values.
      VariationDimensions.new(variation_dimension)
    end
  end
end
