# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AwseCommerceService
  # VariationAttributes Model.
  class VariationAttributes < BaseModel
    # TODO: Write general description for this method
    # @return [List of VariationAttribute]
    attr_accessor :variation_attribute

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['variation_attribute'] = 'VariationAttribute'
      @_hash
    end

    def initialize(variation_attribute = nil)
      @variation_attribute = variation_attribute
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      variation_attribute = nil
      unless hash['VariationAttribute'].nil?
        variation_attribute = []
        hash['VariationAttribute'].each do |structure|
          variation_attribute << (VariationAttribute.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      VariationAttributes.new(variation_attribute)
    end
  end
end
