//
//  GetCalculateInput.h
//  APIMATICCalculator
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_GETCALCULATEINPUT
#define APIMATIC_GETCALCULATEINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "OperationTypeEnum.h"
#import "OperationTypeEnumHelper.h"


//protocol defined for deserialization of JSON
@protocol GetCalculateInput
@end

@interface GetCalculateInput : NSObject

/**
* The operator to apply on the variables
*/
@property enum OperationTypeEnum operation;

/**
* The LHS value
*/
@property NSObject* x;

/**
* The RHS value
*/
@property double y;

@end
#endif