//
//  OperationTypeEnum.h
//  APIMATICCalculator
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#include "OperationTypeEnumHelper.h"

/**
* Helper class implementation for OperationTypeEnum to NSString conversion
*/
@implementation OperationTypeEnumHelper

+(id) stringFromOperationTypeEnum:(enum OperationTypeEnum) operationTypeEnum withDefault: (id) defaultValue
{
    switch(operationTypeEnum)
    {
        case OperationTypeSUM:
            return @"SUM";

        case OperationTypeSUBTRACT:
            return @"SUBTRACT";

        case OperationTypeMULTIPLY:
            return @"MULTIPLY";

        case OperationTypeDIVIDE:
            return @"DIVIDE";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromOperationTypeEnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [OperationTypeEnumHelper stringFromOperationTypeEnum:(enum OperationTypeEnum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum OperationTypeEnum) operationTypeEnumFromString:(NSString*) strValue
{
    NSArray* OperationTypeEnumArray = [NSArray arrayWithObjects:
                                        @"SUM",
                                        @"SUBTRACT",
                                        @"MULTIPLY",
                                        @"DIVIDE",
                                        nil];

    return (enum OperationTypeEnum) [OperationTypeEnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) operationTypeEnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ OperationTypeEnumHelper operationTypeEnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end