/*
 * apimaticcalculator_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package apimaticcalculator_lib

/** The base Uri for API calls */
const BASEURI string = "http://examples.apimatic.io/apps/calculator"

