<?php
/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace APIMATICCalculatorLib\Controllers;

use APIMATICCalculatorLib\APIException;
use APIMATICCalculatorLib\APIHelper;
use APIMATICCalculatorLib\Configuration;
use APIMATICCalculatorLib\Models;
use APIMATICCalculatorLib\Exceptions;
use APIMATICCalculatorLib\Http\HttpRequest;
use APIMATICCalculatorLib\Http\HttpResponse;
use APIMATICCalculatorLib\Http\HttpMethod;
use APIMATICCalculatorLib\Http\HttpContext;
use Unirest\Request;

/**
 * @todo Add a general description for this controller.
 */
class FghfghfghfghfghfghfghfghfghfghController extends BaseController
{
    /**
     * @var FghfghfghfghfghfghfghfghfghfghController The reference to *Singleton* instance of this class
     */
    private static $instance;

    /**
     * Returns the *Singleton* instance of this class.
     * @return FghfghfghfghfghfghfghfghfghfghController The *Singleton* instance.
     */
    public static function getInstance()
    {
        if (null === static::$instance) {
            static::$instance = new static();
        }
        
        return static::$instance;
    }

    /**
     * @todo Add general description for this endpoint
     *
     * @param  array  $options    Array with all options for search
     * @param Models\TrtrRequest $options['body']          TODO: type description here
     * @param string             $options['cacheControl']  TODO: type description here
     * @param string             $options['contentType']   TODO: type description here
     * @param string             $options['postmanToken']  TODO: type description here
     * @param string             $options['xPassword']     TODO: type description here
     * @param string             $options['xUsername']     TODO: type description here
     * @return mixed response from the API call
     * @throws APIException Thrown if API call fails
     */
    public function createFghfghfghfgh(
        $options
    ) {

        //the base uri for api requests
        $_queryBuilder = Configuration::$BASEURI;
        
        //prepare query string for API call
        $_queryBuilder = $_queryBuilder.'/pushnow';

        //validate and preprocess url
        $_queryUrl = APIHelper::cleanUrl($_queryBuilder);

        //prepare headers
        $_headers = array (
            'user-agent'    => 'APIMATIC 2.0',
            'Accept'        => 'application/json',
            'content-type'  => 'application/json; charset=utf-8',
            'Cache-Control'   => $this->val($options, 'cacheControl'),
            'Content-Type'    => $this->val($options, 'contentType'),
            'Postman-Token'   => $this->val($options, 'postmanToken'),
            'x-password'      => $this->val($options, 'xPassword'),
            'x-username'      => $this->val($options, 'xUsername')
        );

        //call on-before Http callback
        $_httpRequest = new HttpRequest(HttpMethod::POST, $_headers, $_queryUrl);
        if ($this->getHttpCallBack() != null) {
            $this->getHttpCallBack()->callOnBeforeRequest($_httpRequest);
        }

        //and invoke the API call request to fetch the response
        $response = Request::post($_queryUrl, $_headers, Request\Body::Json($this->val($options, 'body')));

        $_httpResponse = new HttpResponse($response->code, $response->headers, $response->raw_body);
        $_httpContext = new HttpContext($_httpRequest, $_httpResponse);

        //call on-after Http callback
        if ($this->getHttpCallBack() != null) {
            $this->getHttpCallBack()->callOnAfterRequest($_httpContext);
        }

        //handle errors defined at the API level
        $this->validateResponse($_httpResponse, $_httpContext);

        return $response->body;
    }


    /**
    * Array access utility method
     * @param  array          $arr         Array of values to read from
     * @param  string         $key         Key to get the value from the array
     * @param  mixed|null     $default     Default value to use if the key was not found
     * @return mixed
     */
    private function val($arr, $key, $default = null)
    {
        if (isset($arr[$key])) {
            return is_bool($arr[$key]) ? var_export($arr[$key], true) : $arr[$key];
        }
        return $default;
    }
}
