/*
 * APIMATICCalculator.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using APIMATICCalculator.UWP.Controllers;
using APIMATICCalculator.UWP.Http.Client;
using APIMATICCalculator.UWP.Utilities;

namespace APIMATICCalculator.UWP
{
    public partial class APIMATICCalculatorClient
    {

        /// <summary>
        /// Singleton access to SimpleCalculator controller
        /// </summary>
        public SimpleCalculatorController SimpleCalculator
        {
            get
            {
                return SimpleCalculatorController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public APIMATICCalculatorClient() { }
        #endregion
    }
}