//
//  Configuration.m
//  APIMATICCalculator
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "Configuration.h"

/** The base Uri for API calls */
NSString* Configuration_BaseUri = @"http://examples.apimatic.io/apps/calculator";

