//
//  Configuration.h
//  APIMATICCalculator
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATICCalculator_Configuration_h
#define APIMATICCalculator_Configuration_h

/** The base Uri for API calls */
extern NSString* Configuration_BaseUri;

#endif
