/*
 * apimaticcalculator_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package simplecalculator_pkg


/*
 * Interface for the SIMPLECALCULATOR_IMPL
 */
type SIMPLECALCULATOR interface {
    GetCalculate (*GetCalculateInput) (float64, error)
}

/*
 * Factory for the SIMPLECALCULATOR interaface returning SIMPLECALCULATOR_IMPL
 */
func NewSIMPLECALCULATOR() SIMPLECALCULATOR {
    return &SIMPLECALCULATOR_IMPL{}
}