<?php
/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace APIMATICCalculatorLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Ds implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $dsfSDFSD public property
     */
    public $dsfSDFSD;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $sdfsdfsdfsdf public property
     */
    public $sdfsdfsdfsdf;

    /**
     * @todo Write general description for this property
     * @required
     * @var \APIMATICCalculatorLib\Models\Sdfsdf $sdfsdf public property
     */
    public $sdfsdf;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $sdfsdfSDFSDFSDFSDF public property
     */
    public $sdfsdfSDFSDFSDFSDF;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $dsfSDFSD           Initialization value for $this->dsfSDFSD
     * @param string $sdfsdfsdfsdf       Initialization value for $this->sdfsdfsdfsdf
     * @param Sdfsdf $sdfsdf             Initialization value for $this->sdfsdf
     * @param string $sdfsdfSDFSDFSDFSDF Initialization value for $this->sdfsdfSDFSDFSDFSDF
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->dsfSDFSD           = func_get_arg(0);
            $this->sdfsdfsdfsdf       = func_get_arg(1);
            $this->sdfsdf             = func_get_arg(2);
            $this->sdfsdfSDFSDFSDFSDF = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['dsfSDFSD']           = $this->dsfSDFSD;
        $json['sdfsdfsdfsdf']       = $this->sdfsdfsdfsdf;
        $json['sdfsdf']             = $this->sdfsdf;
        $json['sdfsdfSDFSDFSDFSDF'] = $this->sdfsdfSDFSDFSDFSDF;

        return $json;
    }
}
