<?php
/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace APIMATICCalculatorLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Erewr implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $asdasD public property
     */
    public $asdasD;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $sadasd public property
     */
    public $sadasd;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $cczxxc public property
     */
    public $cczxxc;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $asdasD Initialization value for $this->asdasD
     * @param string $sadasd Initialization value for $this->sadasd
     * @param string $cczxxc Initialization value for $this->cczxxc
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->asdasD = func_get_arg(0);
            $this->sadasd = func_get_arg(1);
            $this->cczxxc = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['asdasD'] = $this->asdasD;
        $json['sadasd'] = $this->sadasd;
        $json['cczxxc'] = $this->cczxxc;

        return $json;
    }
}
