<?php
/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace APIMATICCalculatorLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Nestedone implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $asd public property
     */
    public $asd;

    /**
     * @todo Write general description for this property
     * @required
     * @maps as
     * @var string $mas public property
     */
    public $mas;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $qw public property
     */
    public $qw;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $wq public property
     */
    public $wq;

    /**
     * @todo Write general description for this property
     * @required
     * @var \APIMATICCalculatorLib\Models\Ds $ds public property
     */
    public $ds;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $azaxasxsd public property
     */
    public $azaxasxsd;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $asd       Initialization value for $this->asd
     * @param string $mas       Initialization value for $this->mas
     * @param string $qw        Initialization value for $this->qw
     * @param string $wq        Initialization value for $this->wq
     * @param Ds     $ds        Initialization value for $this->ds
     * @param string $azaxasxsd Initialization value for $this->azaxasxsd
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->asd       = func_get_arg(0);
            $this->mas       = func_get_arg(1);
            $this->qw        = func_get_arg(2);
            $this->wq        = func_get_arg(3);
            $this->ds        = func_get_arg(4);
            $this->azaxasxsd = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['asd']       = $this->asd;
        $json['as']        = $this->mas;
        $json['qw']        = $this->qw;
        $json['wq']        = $this->wq;
        $json['ds']        = $this->ds;
        $json['azaxasxsd'] = $this->azaxasxsd;

        return $json;
    }
}
