<?php
/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace APIMATICCalculatorLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Sdfsdf implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $dsf public property
     */
    public $dsf;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $dsf Initialization value for $this->dsf
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->dsf = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['dsf'] = $this->dsf;

        return $json;
    }
}
