<?php
/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace APIMATICCalculatorLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class TrtrRequest implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $email public property
     */
    public $email;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $branch public property
     */
    public $branch;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $extractZip public property
     */
    public $extractZip;

    /**
     * @todo Write general description for this property
     * @required
     * @var \APIMATICCalculatorLib\Models\FileInfo $fileInfo public property
     */
    public $fileInfo;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $repoUrl public property
     */
    public $repoUrl;

    /**
     * Constructor to set initial or default values of member properties
     * @param string   $email      Initialization value for $this->email
     * @param string   $name       Initialization value for $this->name
     * @param string   $branch     Initialization value for $this->branch
     * @param bool     $extractZip Initialization value for $this->extractZip
     * @param FileInfo $fileInfo   Initialization value for $this->fileInfo
     * @param string   $repoUrl    Initialization value for $this->repoUrl
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->email      = func_get_arg(0);
            $this->name       = func_get_arg(1);
            $this->branch     = func_get_arg(2);
            $this->extractZip = func_get_arg(3);
            $this->fileInfo   = func_get_arg(4);
            $this->repoUrl    = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['email']      = $this->email;
        $json['name']       = $this->name;
        $json['branch']     = $this->branch;
        $json['extractZip'] = $this->extractZip;
        $json['fileInfo']   = $this->fileInfo;
        $json['repoUrl']    = $this->repoUrl;

        return $json;
    }
}
