<?php
/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace APIMATICCalculatorLib;

use APIMATICCalculatorLib\Controllers;

/**
 * APIMATICCalculatorLib client class
 */
class APIMATICCalculatorClient
{
    /**
     * Singleton access to SimpleCalculator controller
     * @return Controllers\SimpleCalculatorController The *Singleton* instance
     */
    public function getSimpleCalculator()
    {
        return Controllers\SimpleCalculatorController::getInstance();
    }
    /**
     * Singleton access to Fghfghfghfghfghfghfghfghfghfgh controller
     * @return Controllers\FghfghfghfghfghfghfghfghfghfghController The *Singleton* instance
     */
    public function getFghfghfghfghfghfghfghfghfghfgh()
    {
        return Controllers\FghfghfghfghfghfghfghfghfghfghController::getInstance();
    }
}
